# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '^(.*\.svg)$'
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: '^(.*\.svg)$'
      - id: trailing-whitespace
        exclude: '^(|.*\.svg)$'
      - id: fix-byte-order-marker
      - id: no-commit-to-branch
      - id: requirements-txt-fixer

  - repo: local
    hooks:
      - id: clang-format-fix
        name: clang-format-fix
        entry: clang-format-18
        files: ^(src/|include/)
        types_or: [c++, c]
        language: system
        args: ['-i']
        stages: [manual]

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        additional_dependencies: ['clang-format==18.1.8']
      # - id: oclint
      # - id: cppcheck
      # - id: cpplint

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        stages: [manual]
        additional_dependencies: ['clang-tidy==18.1.8']

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ['-I', '.codespell_ignore', '--uri-ignore-words-list']
        exclude: |
          (?x)^(
            papers/.*
          )$

  # CMake formatting
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: "v0.6.13"
    hooks:
      - id: cmake-format
        additional_dependencies: [pyyaml]
      - id: cmake-lint

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
      - id: gitlint-ci

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

exclude: 'vendor'
