# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
        exclude: ^\.clang-format$
    -   id: check-added-large-files

    # Clang-format for C++
    # This brings in a portable version of clang-format.
    # See also: https://github.com/ssciwr/clang-format-wheel
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
    - id: clang-format
      types_or: [c++, c, json]

    # CMake linting and formatting
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.17.0
    hooks:
    - id: gersemi
      name: CMake linting

    # Markdown linting
    # Config file: .markdownlint.yaml
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
    - id: markdownlint
      exclude: ^papers/

    # Config file: .codespell_ignore
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ['-I', '.codespell_ignore', '--uri-ignore-words-list']
        exclude: |
          (?x)^(
            papers/.*
          )$
